### ISSUE TITLE
Default test case fails for new alert

### ISSUE THREAD

**Issue by darakian** [mozilla/MozDef#979] opened 2018-11-27 18:13 UTC
Hey all,

I'm just getting into making alerts and I wanted to mention that if you run 
```
make new-alert
```
and then try to run the associated test you will be left with a failing test due to the line 
```
"notify_mozdefbot": False,
```
This is a bit confusing for people new to alert writing and being such a new person, I'm not sure if this is desired behavior or not. Either way I wanted to make a note for those searching around.

**Comment by jeffbryner** [comment] 2018-11-27 18:21
That's a good catch. I ran into the same thing and made a change to the template here: 
https://github.com/mozilla/MozDef/pull/974/commits/46b1e849febb958f33c6e3555323c24addd01563

@pwnbus any idea why the tests require this, but the alerts don't?

**Comment by darakian** [comment] 2018-11-27 18:49
Sure thing. I'm still just trying to come to grips with how to use MozDef. I'm not getting any alerts at all right now, so I'll probably make a PR for an extra page of documentation once I wrap my head around it.

**Comment by jeffbryner** [comment] 2018-11-27 18:57
Excellent, newcomer points of view are just the ticket for accurate docs! ;-] (protip; check timestamps if you know you have data but they aren't alerting. We do our best to get everything to UTC, but if source doesn't have timezone and not operating in UTC it can cause 'missing' alerts)

**Comment by darakian** [comment] 2018-11-27 19:12
So, I'm trying to get a basic alert to work for logs coming in from rsyslog. I've modified the default alert to
```
        search_query.add_must([
            TermMatch('category', 'rsyslog'),
            ExistsMatch('hostname'),
        ])
```
Full source below.

I read this to mean "put an alert on mozdefhost/alerts" if there exist logs with the category=='rsyslog' and something non-null for a hostname (and with timestamps within 20 minutes of "now" for now being the time runtime of the query).

I can check the Kibana instance (this is all a MozDef demo docker thing) and such logs exist. In fact I've extended the time range to be 2000 minutes and I still don't see anything on the alerts page. I feel like I'm missing something basic here.



```
#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# Copyright (c) 2014 Mozilla Corporation


from lib.alerttask import AlertTask
from mozdef_util.query_models import SearchQuery, TermMatch, QueryStringMatch, ExistsMatch, PhraseMatch, WildcardMatch


class AlertRsyslog(AlertTask):
    def main(self):
        # Create a query to look back the last 20 minutes
        search_query = SearchQuery(minutes=2000)

        # Add search terms to our query
        search_query.add_must([
            TermMatch('category', 'rsyslog-json'),
            ExistsMatch('hostname'),
        ])

        self.filtersManual(search_query)
        # Search aggregations on field 'hostname'
        # keep X samples of events at most
        self.searchEventsAggregated('details.hostname', samplesLimit=10)
        # alert when >= X matching events in an aggregation
        self.walkAggregations(threshold=1)

    # Set alert properties
    def onAggregation(self, aggreg):
        # aggreg['count']: number of items in the aggregation, ex: number of failed login attempts
        # aggreg['value']: value of the aggregation field, ex: toto@example.com
        # aggreg['events']: list of events in the aggregation
        category = 'rsyslogcategory'
        tags = ['hello', 'world', 'rsyslog']
        severity = 'WARNING'
        summary = "My first alert!"

        # Create the alert object based on these properties
        return self.createAlertDict(summary, category, tags, aggreg['events'], severity)
```

**Comment by pwnbus** [comment] 2018-11-27 19:22
@jeffbryner The tests require that field to be set when alerts are INFO level or lower. The reason this field exists, is to determine whether or not the bot should receive this alert.

We can change the default to be, notify_mozdefbot = False, but then we have to specify this field for every alert that is WARNING or higher.

**Comment by pwnbus** [comment] 2018-11-27 19:32
@jeffbryner @darakian  https://github.com/mozilla/MozDef/pull/975/files#diff-fc564a2df4483f88fb7ac9a26d9be17dR32 is the regression that this is now causing those templated tests to fail. I'll have a PR up shortly that will fix that.

**Comment by pwnbus** [comment] 2018-11-27 20:07
Fixed in https://github.com/mozilla/MozDef/pull/981

**Comment by pwnbus** [comment] 2018-11-27 21:00
This has been merged, so I'm closing the issue.

@darakian In order to enable the alert, you need to modify https://github.com/mozilla/MozDef/blob/master/alerts/lib/config.py#L13 . If you're using docker, you can temporarily enable it by modifying the corresponding config.py file in docker -> https://github.com/mozilla/MozDef/blob/master/docker/compose/mozdef_alerts/files/config.py

**Closed by pwnbus** 2018-11-27 21:00 UTC
Labels: category:bug

**Comment by pwnbus** [comment] 2018-11-27 21:44
@darakian Yes, there needs to be one line per alert that you want to enable.

Currently, the only supported way is to modify this file https://github.com/mozilla/MozDef/blob/master/docker/compose/mozdef_alerts/files/config.py on disk before building/running, we don't support passing in that list via environment variables or anything (I just created https://github.com/mozilla/MozDef/issues/982 to add that support).
